import { useState, useEffect } from 'react';
import api from '../../lib/api';

export default function RiskAnalysisPanel({ claimId }) {
    const [analysis, setAnalysis] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (claimId) fetchRiskAnalysis();
    }, [claimId]);

    const fetchRiskAnalysis = async () => {
        try {
            const response = await api.get(`/claims/${claimId}/risk`);
            setAnalysis(response.data);
        } catch (error) {
            console.error("Failed to fetch risk analysis", error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) return <div className="h-32 bg-muted animate-pulse rounded-xl"></div>;
    if (!analysis) return null;

    const { riskAnalysis, draftPatta } = analysis;

    return (
        <div className="space-y-6">
            {/* Risk Score Card */}
            <div className={`border-l-4 rounded-r-xl p-4 shadow-sm ${riskAnalysis.level === 'CRITICAL' ? 'bg-red-50 border-red-500' :
                    riskAnalysis.level === 'HIGH' ? 'bg-orange-50 border-orange-500' :
                        riskAnalysis.level === 'MEDIUM' ? 'bg-yellow-50 border-yellow-500' :
                            'bg-green-50 border-green-500'
                }`}>
                <div className="flex justify-between items-start">
                    <div>
                        <h3 className="font-bold text-lg flex items-center gap-2">
                            {riskAnalysis.level === 'CRITICAL' && '⛔'}
                            {riskAnalysis.level === 'HIGH' && '⚠️'}
                            {riskAnalysis.level === 'MEDIUM' && '✋'}
                            {riskAnalysis.level === 'LOW' && '✅'}
                            Risk Level: {riskAnalysis.level}
                        </h3>
                        <p className="text-sm opacity-80 mt-1">Risk Score: {riskAnalysis.score}/100</p>
                    </div>
                </div>

                {riskAnalysis.flags.length > 0 && (
                    <ul className="mt-3 space-y-2">
                        {riskAnalysis.flags.map((flag, idx) => (
                            <li key={idx} className="text-sm flex items-start gap-2">
                                <span className="mt-0.5">•</span>
                                <span>{flag.message}</span>
                            </li>
                        ))}
                    </ul>
                )}
            </div>

            {/* Auto-Drafted Patta */}
            {draftPatta && (
                <div className="bg-card border border-border rounded-xl p-6">
                    <div className="flex justify-between items-center mb-4">
                        <h3 className="font-bold text-lg">📜 Auto-Drafted Title Deed (Patta)</h3>
                        <button
                            onClick={() => navigator.clipboard.writeText(draftPatta)}
                            className="text-xs bg-secondary px-2 py-1 rounded hover:bg-secondary/80"
                        >
                            Copy Text
                        </button>
                    </div>
                    <div className="bg-muted/30 p-4 rounded-lg text-sm font-mono whitespace-pre-wrap max-h-60 overflow-y-auto border border-border">
                        {draftPatta}
                    </div>
                    <p className="text-xs text-muted-foreground mt-2 text-center">
                        Generated by AI based on claim details. Please verify before signing.
                    </p>
                </div>
            )}
        </div>
    );
}
